const NPC_MET_FLAG_TO_ID = {
  met_spice_trader: "spice_trader",
  met_weapons_dealer: "weapons_dealer",
  met_map_seller: "map_seller",
  met_fence: "fence",
  met_exotic_trader: "exotic_trader",
  met_shipwright: "shipwright",
  met_rum_merchant: "rum_merchant",
  met_rival_captain: "rival_captain",
  met_bones: "first_mate_bones",
  met_pirate_queen: "pirate_queen",
  met_legendary_pirate: "legendary_pirate",
  met_retired_pirate: "retired_pirate",
  met_smuggler: "smuggler",
  met_mutineer: "mutineer",
  met_governor: "governor",
  met_navy_captain: "navy_captain",
  met_customs_officer: "customs_officer",
  met_judge: "judge",
  met_voodoo_priestess: "voodoo_priestess",
  met_fortune_teller: "fortune_teller",
  met_cursed_sailor: "cursed_sailor",
  met_sea_witch: "sea_witch",
  met_hermit_monk: "hermit_monk",
  met_surgeon: "surgeon",
  met_navigator: "navigator",
  met_cook: "cook",
  met_gunner: "gunner",
  met_bosun: "bosun",
  met_fisherman: "fisherman",
  met_plantation_owner: "plantation_owner",
  met_priest: "priest",
  met_tavern_keeper: "tavern_keeper",
  met_ghost_captain: "ghost_captain",
  met_siren: "siren",
  met_sea_god: "sea_god",
  met_skeleton_crew: "skeleton_crew",
} as const;

export function findNpcIdByMetFlag(flag: string): string | null {
  return NPC_MET_FLAG_TO_ID[flag as keyof typeof NPC_MET_FLAG_TO_ID] ?? null;
}
